import { API_PREFIX } from '../api/api.constants';

export const DEMO_MONEY_OWNER_PARAM = 'owner';

export const DEMO_MONEY_ROUTE_ME = 'me';
export const DEMO_MONEY_ROUTE_ACCOUNTS = 'accounts';
export const DEMO_MONEY_ROUTE_ACCOUNT_BY_OWNER = `${DEMO_MONEY_ROUTE_ACCOUNTS}/:${DEMO_MONEY_OWNER_PARAM}`;
export const DEMO_MONEY_ROUTE_ISSUE_ACCOUNT = `${DEMO_MONEY_ROUTE_ACCOUNTS}/issue`;
export const DEMO_MONEY_ROUTE_ADJUST_BALANCE = `${DEMO_MONEY_ROUTE_ACCOUNTS}/adjust-balance`;
export const DEMO_MONEY_ROUTE_PENDING_TRANSFERS = 'transfers/pending';
export const DEMO_MONEY_ROUTE_REQUEST_TRANSFER = 'transfers/request';
export const DEMO_MONEY_ROUTE_PROCESS_TRANSFERS = 'transfers/process';

const DEMO_MONEY_API_BASE_PATH = `/${API_PREFIX}`;

export const DEMO_MONEY_ME_PATH = `${DEMO_MONEY_API_BASE_PATH}/${DEMO_MONEY_ROUTE_ME}`;
export const DEMO_MONEY_ACCOUNTS_PATH = `${DEMO_MONEY_API_BASE_PATH}/${DEMO_MONEY_ROUTE_ACCOUNTS}`;
export const DEMO_MONEY_ISSUE_ACCOUNT_PATH = `${DEMO_MONEY_API_BASE_PATH}/${DEMO_MONEY_ROUTE_ISSUE_ACCOUNT}`;
export const DEMO_MONEY_ADJUST_BALANCE_PATH = `${DEMO_MONEY_API_BASE_PATH}/${DEMO_MONEY_ROUTE_ADJUST_BALANCE}`;
export const DEMO_MONEY_PENDING_TRANSFERS_PATH = `${DEMO_MONEY_API_BASE_PATH}/${DEMO_MONEY_ROUTE_PENDING_TRANSFERS}`;
export const DEMO_MONEY_REQUEST_TRANSFER_PATH = `${DEMO_MONEY_API_BASE_PATH}/${DEMO_MONEY_ROUTE_REQUEST_TRANSFER}`;
export const DEMO_MONEY_PROCESS_TRANSFERS_PATH = `${DEMO_MONEY_API_BASE_PATH}/${DEMO_MONEY_ROUTE_PROCESS_TRANSFERS}`;
