canton {
  remote-participants {
    bank {
      ledger-api {
        address = "participant-bank"
        port = 5011
      }
      admin-api {
        address = "participant-bank"
        port = 5012
      }
    }

    users {
      ledger-api {
        address = "participant-users"
        port = 5011
      }
      admin-api {
        address = "participant-users"
        port = 5012
      }
    }

    observer {
      ledger-api {
        address = "participant-observer"
        port = 5011
      }
      admin-api {
        address = "participant-observer"
        port = 5012
      }
    }
  }
}
