include required("/canton/config/storage/h2.conf")

canton {
  participants {
    participant-users {
      storage = ${_shared.storage}
      storage.config.properties.databaseName = "/data/participant-users"

      ledger-api {
        address = "0.0.0.0"
        port = 5011
        auth-services = [
          {
            type = jwt-jwks
            url = "http://keycloak:8080/realms/canton-demo/protocol/openid-connect/certs"
            target-scope = "canton_demo_admin"
            privileged = true
            access-level = wildcard
          },
          {
            type = jwt-jwks
            url = "http://keycloak:8080/realms/canton-demo/protocol/openid-connect/certs"
            target-scope = "daml_ledger_api"
          }
        ]
      }

      http-ledger-api {
        enabled = true
        address = "0.0.0.0"
        port = 5013
      }

      admin-api {
        address = "0.0.0.0"
        port = 5012
      }
    }
  }
}
