include required("/canton/config/storage/h2.conf")

canton {
  sequencers {
    sequencer1 {
      storage = ${_shared.storage}
      storage.config.properties.databaseName = "/data/sequencer1"

      public-api {
        address = "0.0.0.0"
        port = 5001
      }

      admin-api {
        address = "0.0.0.0"
        port = 5002
      }

      sequencer.type = BFT
    }
  }

  mediators {
    mediator1 {
      storage = ${_shared.storage}
      storage.config.properties.databaseName = "/data/mediator1"

      admin-api {
        address = "0.0.0.0"
        port = 5202
      }
    }
  }
}
